<?php
namespace Heystack\Ecommerce\DependencyInjection;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 16:58:14.
 */
class ContainerExtensionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ContainerExtension
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new ContainerExtension;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heystack\Ecommerce\DependencyInjection\ContainerExtension::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Ecommerce\DependencyInjection\ContainerExtension::getNamespace
     * @todo   Implement testGetNamespace().
     */
    public function testGetNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Ecommerce\DependencyInjection\ContainerExtension::getXsdValidationBasePath
     * @todo   Implement testGetXsdValidationBasePath().
     */
    public function testGetXsdValidationBasePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Ecommerce\DependencyInjection\ContainerExtension::getAlias
     * @todo   Implement testGetAlias().
     */
    public function testGetAlias()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
