<?php
namespace Heystack\Subsystem\Ecommerce\Currency;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 16:57:48.
 */
class CurrencyServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CurrencyService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new CurrencyService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\CurrencyService::restoreState
     * @todo   Implement testRestoreState().
     */
    public function testRestoreState()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\CurrencyService::saveState
     * @todo   Implement testSaveState().
     */
    public function testSaveState()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\CurrencyService::setActiveCurrency
     * @todo   Implement testSetActiveCurrency().
     */
    public function testSetActiveCurrency()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\CurrencyService::getActiveCurrency
     * @todo   Implement testGetActiveCurrency().
     */
    public function testGetActiveCurrency()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\CurrencyService::getActiveCurrencyCode
     * @todo   Implement testGetActiveCurrencyCode().
     */
    public function testGetActiveCurrencyCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\CurrencyService::getCurrencies
     * @todo   Implement testGetCurrencies().
     */
    public function testGetCurrencies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\CurrencyService::convert
     * @todo   Implement testConvert().
     */
    public function testConvert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\CurrencyService::getCurrency
     * @todo   Implement testGetCurrency().
     */
    public function testGetCurrency()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\CurrencyService::getDefaultCurrency
     * @todo   Implement testGetDefaultCurrency().
     */
    public function testGetDefaultCurrency()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\CurrencyService::setDefaultCurrency
     * @todo   Implement testSetDefaultCurrency().
     */
    public function testSetDefaultCurrency()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
