<?php
namespace Heystack\Subsystem\Ecommerce\Locale;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 16:58:25.
 */
class LocaleServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LocaleService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new LocaleService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Locale\LocaleService::setCountries
     * @todo   Implement testSetCountries().
     */
    public function testSetCountries()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Locale\LocaleService::addCountry
     * @todo   Implement testAddCountry().
     */
    public function testAddCountry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Locale\LocaleService::restoreState
     * @todo   Implement testRestoreState().
     */
    public function testRestoreState()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Locale\LocaleService::saveState
     * @todo   Implement testSaveState().
     */
    public function testSaveState()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Locale\LocaleService::setActiveCountry
     * @todo   Implement testSetActiveCountry().
     */
    public function testSetActiveCountry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Locale\LocaleService::getActiveCountry
     * @todo   Implement testGetActiveCountry().
     */
    public function testGetActiveCountry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Locale\LocaleService::getCountry
     * @todo   Implement testGetCountry().
     */
    public function testGetCountry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Locale\LocaleService::getCountries
     * @todo   Implement testGetCountries().
     */
    public function testGetCountries()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Locale\LocaleService::setDefaultCountry
     * @todo   Implement testSetDefaultCountry().
     */
    public function testSetDefaultCountry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Locale\LocaleService::getDefaultCountry
     * @todo   Implement testGetDefaultCountry().
     */
    public function testGetDefaultCountry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
