<?php
namespace Heystack\Subsystem\Ecommerce\Currency\Event;

use Heystack\Subsystem\Ecommerce\Currency\Interfaces\CurrencyInterface;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 16:57:50.
 */
class CurrencyEventTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CurrencyEvent
     */
    protected $currencyEvent;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $nzCurrency = $this->getMock('Heystack\Subsystem\Ecommerce\Currency\Interfaces\CurrencyInterface');

        $this->currencyEvent = new CurrencyEvent($nzCurrency);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->currencyEvent = null;
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\Event\CurrencyEvent::getCurrency
     */
    public function testGetCurrency()
    {
        $nzCurrency = $this->currencyEvent->getCurrency();

        $this->assertTrue($nzCurrency instanceof CurrencyInterface);
    }
}
