<?php
namespace Heystack\Subsystem\Ecommerce\Currency\Event;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 16:57:50.
 */
class CurrencyEventTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CurrencyEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new CurrencyEvent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heystack\Subsystem\Ecommerce\Currency\Event\CurrencyEvent::getCurrency
     * @todo   Implement testGetCurrency().
     */
    public function testGetCurrency()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
