<?php
namespace Heystack\Ecommerce\Transaction;

use Heystack\Core\Storage\Backends\SilverStripeOrm\Backend;
use Heystack\Core\ViewableData\ViewableDataInterface;
use Heystack\Ecommerce\Transaction\Interfaces\TransactionModifierInterface;
use SebastianBergmann\Money\NZD;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 16:59:00.
 */
class TransactionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Transaction
     */
    protected $transaction;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $currencyService = $this->getMockBuilder('Heystack\Ecommerce\Currency\CurrencyService')
            ->disableOriginalConstructor()
            ->getMock();
        $currencyService->expects($this->any())
            ->method('getZeroMoney')
            ->will($this->returnValue(new NZD(0)));
        $currencyService->expects($this->any())
            ->method('getActiveCurrencyCode')
            ->will($this->returnValue('NZD'));

        $stateService = $this->getMockBuilder('Heystack\Core\State\State')
            ->disableOriginalConstructor()
            ->getMock();

        $modifierIdentifier = $this->getMockBuilder('Heystack\Core\Identifier\Identifier')
            ->disableOriginalConstructor()
            ->getMock();
        $modifierIdentifier->expects($this->any())
            ->method('getFull')
            ->will($this->returnValue('purchasableholder'));

        $modifier = $this->getMock('Heystack\Ecommerce\Transaction\Interfaces\TransactionModifierInterface');
        $modifier->expects($this->any())
            ->method('getIdentifier')
            ->will($this->returnValue($modifierIdentifier));
        $modifier->expects($this->any())
            ->method('getType')
            ->will($this->returnValue('chargeable'));
        $modifier->expects($this->any())
            ->method('getTotal')
            ->will($this->returnValue(new NZD(100)));

        $this->transaction = new Transaction(
            $stateService,
            $currencyService,
            ['Pending', 'Successful', 'Failed', 'Dispatched', 'Processing', 'Cancelled'],
            'Pending'
        );

        $this->transaction->addModifier($modifier);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->transaction = null;
    }

    /**
     * @covers Heystack\Ecommerce\Transaction\Transaction::__construct
     * @covers Heystack\Ecommerce\Transaction\Transaction::addModifier
     * @covers Heystack\Ecommerce\Transaction\Transaction::getModifier
     * @covers Heystack\Ecommerce\Transaction\Transaction::getModifiers
     * @covers Heystack\Ecommerce\Transaction\Transaction::getModifiersByType
     */
    public function testModifiersAccess()
    {
        $modifierIdentifier = $this->getMockBuilder('Heystack\Core\Identifier\Identifier')
            ->disableOriginalConstructor()
            ->getMock();
        $modifierIdentifier->expects($this->any())
            ->method('getFull')
            ->will($this->returnValue('taxhandler'));

        $modifier = $this->getMock('Heystack\Ecommerce\Transaction\Interfaces\TransactionModifierInterface');
        $modifier->expects($this->any())
            ->method('getIdentifier')
            ->will($this->returnValue($modifierIdentifier));
        $modifier->expects($this->any())
            ->method('getType')
            ->will($this->returnValue('deductible'));

        $this->transaction->addModifier($modifier);

        $this->assertTrue($this->transaction->getModifier($modifierIdentifier->getFull()) instanceof TransactionModifierInterface);

        $this->assertContainsOnlyInstancesOf(
            'Heystack\Ecommerce\Transaction\Interfaces\TransactionModifierInterface',
            $this->transaction->getModifiers()
        );

        $this->assertContainsOnlyInstancesOf(
            'Heystack\Ecommerce\Transaction\Interfaces\TransactionModifierInterface',
            $this->transaction->getModifiersByType('deductible')
        );
    }

    /**
     * @covers Heystack\Ecommerce\Transaction\Transaction::getTotal
     * @covers Heystack\Ecommerce\Transaction\Transaction::updateTotal
     */
    public function testGetTotal()
    {
        $this->assertEquals(new NZD(0), $this->transaction->getTotal());

        $this->transaction->updateTotal();

        $this->assertEquals(new NZD(100), $this->transaction->getTotal());

    }

    /**
     * @covers Heystack\Ecommerce\Transaction\Transaction::getTotalWithExclusions
     */
    public function testGetTotalWithExclusions()
    {
        $modifierIdentifier = $this->getMockBuilder('Heystack\Core\Identifier\Identifier')
            ->disableOriginalConstructor()
            ->getMock();
        $modifierIdentifier->expects($this->any())
            ->method('getFull')
            ->will($this->returnValue('voucher'));

        $modifier = $this->getMock('Heystack\Ecommerce\Transaction\Interfaces\TransactionModifierInterface');
        $modifier->expects($this->any())
            ->method('getIdentifier')
            ->will($this->returnValue($modifierIdentifier));
        $modifier->expects($this->any())
            ->method('getType')
            ->will($this->returnValue('deductible'));
        $modifier->expects($this->any())
            ->method('getTotal')
            ->will($this->returnValue(new NZD(50)));

        $this->assertEquals(new NZD(100), $this->transaction->getTotalWithExclusions([]));

        $this->transaction->addModifier($modifier);

        $this->assertEquals(new NZD(50), $this->transaction->getTotalWithExclusions([]));

        $this->assertEquals(new NZD(100), $this->transaction->getTotalWithExclusions(['voucher']));

        $this->assertEquals(new NZD(-50), $this->transaction->getTotalWithExclusions(['purchasableholder']));

    }

    /**
     * @covers Heystack\Ecommerce\Transaction\Transaction::getStorableIdentifier
     */
    public function testGetStorableIdentifier()
    {
        $this->assertEquals(Transaction::IDENTIFIER, $this->transaction->getStorableIdentifier());
    }

    /**
     * @covers Heystack\Ecommerce\Transaction\Transaction::getSchemaName
     */
    public function testGetSchemaName()
    {
        $this->assertEquals('Transaction', $this->transaction->getSchemaName());
    }

    /**
     * @covers Heystack\Ecommerce\Transaction\Transaction::getStorableData
     */
    public function testGetStorableData()
    {
        $storableData = $this->transaction->getStorableData();

        $this->assertCount(3, $storableData);

        $this->assertContains('Transaction', $storableData);
        $this->assertContains('NZD', $storableData['flat']);
        $this->assertContains('Pending', $storableData['flat']);

        $this->assertEquals(0, $storableData['flat']['Total']);

        $this->transaction->updateTotal();
        $storableData = $this->transaction->getStorableData();
        $this->assertEquals(1, $storableData['flat']['Total']);
    }

    /**
     * @covers Heystack\Ecommerce\Transaction\Transaction::getStorableBackendIdentifiers
     */
    public function testGetStorableBackendIdentifiers()
    {
        $this->assertEquals([Backend::IDENTIFIER], $this->transaction->getStorableBackendIdentifiers());
    }

    /**
     * @covers Heystack\Ecommerce\Transaction\Transaction::setStatus
     * @expectedException \InvalidArgumentException
     */
    public function testSetStatus()
    {
        $this->transaction->setStatus('invalid_status');
    }
}
